name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Debug file encoding and contents
        run: |
          file requirements-dev.txt
          cat -A requirements-dev.txt

      - name: Normalize requirements-dev.txt encoding
        run: |
          # Detect UTF-16 LE BOM and convert if present
          if head -c 2 requirements-dev.txt | od -An -tx1 | grep -q 'ff fe'; then
            echo "File is UTF-16 LE, converting to UTF-8"
            iconv -f utf-16le -t utf-8 requirements-dev.txt -o requirements-dev.txt.utf8
            mv requirements-dev.txt.utf8 requirements-dev.txt
          else
            echo "File is NOT UTF-16 LE, stripping UTF-8 BOM if present"
            sed -i '1s/^\xEF\xBB\xBF//' requirements-dev.txt
          fi

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -r requirements-dev.txt

      - name: Lint with black
        run: |
          black --check .

      - name: Run tests
        run: |
          pytest

      - name: Build Docker image
        run: |
          docker build -t fastapi-url-shortener .
